---
title: "test-vignette-for-dev"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{test-vignette-for-dev}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
#library(bayesEpi)
```

# Generate data

```{r ex}
# Packages ----------------------------------------------------------------
library(data.table)
library(tidyverse)
library(RhpcBLASctl)
blas_set_num_threads(1)


# Functions ---------------------------------------------------------------

generateCounts <- function(gen_pars, delta_mat, theta_z, with_intercept = T){
  all_covariates <- c(unlist(gen_pars$linear_covariates),
                      unlist(gen_pars$nonlinear_covariates))
  
  fac_cov <- unlist(gen_pars$factor_covariates)
  all_covariates <- c(all_covariates,
                      unlist(lapply(fac_cov, function(x) grep(x, colnames(delta_mat), value=T))))
  
  if(gen_pars$time_trend[[1]] != "none") all_covariates <- c(all_covariates, gen_pars$time_trend[[1]])
  if(gen_pars$seasonality[[1]] != "none") all_covariates <- c(all_covariates, grep(gen_pars$seasonality[[1]], colnames(delta_mat), value=T))
  if(with_intercept) all_covariates <- c(all_covariates, "(Intercept)")
    
  n <- nrow(delta_mat)
  exp_delta <- exp( rowSums(as.matrix(delta_mat[,all_covariates])) + (gen_pars$overdispersion[[1]] != "none")*rnorm(n,0,1/sqrt(theta_z)) )
  rpois(n, exp_delta)
}


# Generate data -----------------------------------------------------------

  gen_pars <- fread("~/Git/air-pollution-models/R/simulations/simulation-1/generation_grid.csv")[6,]
  gen_pars$nonlinear_covariates <- strsplit(gen_pars$nonlinear_covariates,"|",fixed=T)
  
  # load delta matrix
  delta_mat <- readRDS("~/Git/air-pollution-models/R/simulations/simulation-1/PTS-INLA-1/delta_mat.rds")
  theta_z <- 4
  data <- readRDS("~/Git/air-pollution-models/R/simulations/simulation-1/PTS-INLA-1/data.rds")
  data$count <- generateCounts(gen_pars, delta_mat, theta_z)
  
  model <- ccModel(fixed = list(fixedEffect("hum_mean", gaussian_prior())),
                   random = list(randomEffect("o3_lag", rw_effect()))
```







