# all: cc_rw.so cc_iwp.so
	# comment

#cc_rw.so: cc_rw.cpp
#	Rscript --vanilla -e "TMB::compile('cc_rw.cpp','-O0 -g')"
#cc_iwp.so: cc_iwp.cpp
#	Rscript --vanilla -e "TMB::compile('cc_iwp.cpp','-O0 -g')"

#clean:
#	rm -rf *o
